sonar.projectKey=formalearn
sonar.projectName=FormaLearn
sonar.sourceEncoding=UTF-8

sonar.modules=backend,frontend

backend.sonar.projectName=FormaLearn Backend
backend.sonar.sources=src/main/java
backend.sonar.tests=src/test/java
backend.sonar.java.binaries=target/classes
backend.sonar.coverage.jacoco.xmlReportPaths=target/site/jacoco/jacoco.xml

frontend.sonar.projectName=FormaLearn Frontend
frontend.sonar.sources=src
frontend.sonar.exclusions=**/*.spec.ts,**/environments/**
frontend.sonar.tests=src
frontend.sonar.test.inclusions=**/*.spec.ts
frontend.sonar.javascript.lcov.reportPaths=coverage/lcov.info
