apiVersion: v1
kind: ConfigMap
metadata:
  name: formalearn-config
  namespace: formalearn
data:
  SPRING_PROFILES_ACTIVE: "dev"
  SERVER_PORT: "8080"
  MYSQL_HOST: "mysql"
  MYSQL_PORT: "3306"
  MYSQL_DATABASE: "formation_platform"
  MYSQL_USER: "root"
  ML_BASE_URL: "http://ml:8000"
