apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: formalearn
resources:
  - namespace.yaml
  - configmap.yaml
  - secrets.example.yaml
  - mysql.yaml
  - ml.yaml
  - backend.yaml
  - frontend.yaml
